# Generated by Django 5.2.10 on 2026-04-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('project_type', models.CharField(max_length=100, verbose_name='Type de projet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('location', models.CharField(max_length=200, verbose_name='Localisation')),
                ('category', models.CharField(choices=[('houses', 'Maisons'), ('infrastructure', 'Infrastructure'), ('renovation', 'Rénovation')], max_length=50, verbose_name='Catégorie')),
                ('image_url', models.URLField(max_length=500, verbose_name="URL de l'image")),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(help_text='Ex: apartment, engineering, foundation', max_length=50, verbose_name='Icône (Material Symbol)')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name="URL de l'image")),
                ('reference', models.CharField(help_text='Ex: TDL-CB', max_length=20, verbose_name='Référence')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
