# Generated by Django 5.2.10 on 2026-04-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('project_type', models.CharField(max_length=100, verbose_name='Type de projet')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Budget estimé')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TDL Construction', max_length=100, verbose_name='Nom du site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description courte')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Lien Facebook')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Lien LinkedIn')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Lien Instagram')),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='projects/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image'),
        ),
    ]
