# Generated by Django 5.2.10 on 2026-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0002_quoterequest_sitesetting_remove_project_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(help_text='Ex: Expertise Industrielle', max_length=100, verbose_name='Sous-titre (Badge)')),
                ('title', models.CharField(max_length=200, verbose_name='Titre principal')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Image de fond')),
                ('cta_text', models.CharField(default='Demander un devis', max_length=50, verbose_name='Texte du bouton')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Bannière Hero',
                'verbose_name_plural': 'Bannières Hero',
                'ordering': ['order'],
            },
        ),
    ]
